// <autogenerated>
//   This file was generated by T4 code generator ContractsCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using OSharp.Core;
using OSharp.Utility.Data;
using System.Linq.Expressions;
using System.Threading.Tasks;
using OSharp.Core.Dependency;
using Bode.Services.Core.Dtos.Bnaners;
using Bode.Services.Core.Models.Bnaners;

namespace Bode.Services.Core.Contracts
{
	public partial interface IBnanersContract : IScopeDependency
	{
		                #region Bnaner信息业务

                IQueryable<Bnaner> Bnaners { get; }

                /// <summary>
                /// 保存Bnaner信息(新增/更新)
                /// </summary>
                /// <param name="updateForeignKey">更新时是否更新外键信息</param>
                /// <param name="dtos">要保存的BnanerDto信息</param>
                /// <returns>业务操作集合</returns>
                Task<OperationResult> SaveBnaners(bool updateForeignKey=false,params BnanerDto[] dtos);

                /// <summary>
                /// 删除Bnaner信息
                /// </summary>
                /// <param name="ids">要删除的Id编号</param>
                /// <returns>业务操作结果</returns>
                Task<OperationResult> DeleteBnaners(params int[] ids);

                #endregion

                	}
}
