// <autogenerated>
//   This file was generated by T4 code generator DtosCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using OSharp.Core.Data;
using System.ComponentModel;
using Bode.Services.Core.Models.Config;

namespace Bode.Services.Core.Dtos.Config
{
	public partial class ContactConfigDto: IAddDto, IEditDto<int>
	{
        public System.Int32 Id { get; set; }
                            public System.String Value { get; set; }
                                        public Bode.Services.Core.Models.Config.ContactType Type { get; set; }
                    	}
}
