// <autogenerated>
//   This file was generated by T4 code generator DtosCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using OSharp.Core.Data;
using System.ComponentModel;
using Bode.Services.Core.Models.Student;

namespace Bode.Services.Core.Dtos.Student
{
	public partial class StudentInfoDto: IAddDto, IEditDto<int>
	{
        public System.Int32 Id { get; set; }
                            public System.Int32 UserInfoId { get; set; }
                                        public Bode.Services.Core.Models.Student.Schedule ScheduleState { get; set; }
                                        public System.Int32 JcuId { get; set; }
                                        public System.Int32 JcuSystemId { get; set; }
                                        public System.String UserRealName { get; set; }
                                        public System.String IdCard { get; set; }
                                        public System.String Lng { get; set; }
                                        public System.String Lat { get; set; }
                    	}
}
