// <autogenerated>
//   This file was generated by T4 code generator ServicesCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using OSharp.Core;
using OSharp.Core.Data;
using OSharp.Utility;
using OSharp.Utility.Data;
using OSharp.Utility.Extensions;
using System.Linq.Expressions;
using System.Threading.Tasks;

using Bode.Services.Core.Contracts;
using Bode.Services.Core.Dtos.Wx;
using Bode.Services.Core.Models.Wx;

namespace Bode.Services.Implement.Services
{
	public partial class WxService : IWxContract
	{
		                #region TokenCode信息业务

                public IRepository<TokenCode, int> TokenCodeRepo { protected get; set; }

                public IQueryable<TokenCode> TokenCodes
                {
                    get { return TokenCodeRepo.Entities.Where(p => !p.IsDeleted); }
                }

                /// <summary>
                /// 保存TokenCode信息(新增/更新)
                /// </summary>
                /// <param name="updateForeignKey">更新时是否更新外键信息</param>
                /// <param name="dtos">要保存的TokenCodeDto信息</param>
                /// <returns>业务操作集合</returns>
                public async Task<OperationResult> SaveTokenCodes(bool updateForeignKey=false,params TokenCodeDto[] dtos)
                {
                    try
                    {
                        dtos.CheckNotNull("dtos");
                        var addDtos = dtos.Where(p => p.Id == 0).ToArray();
                        var updateDtos = dtos.Where(p => p.Id != 0).ToArray();

                        TokenCodeRepo.UnitOfWork.TransactionEnabled = true;

                        Action<TokenCodeDto> checkAction=null;
                        Func<TokenCodeDto, TokenCode, TokenCode> updateFunc=null;
                        if (addDtos.Length > 0)
                        {
                            TokenCodeRepo.Insert(addDtos,checkAction,updateFunc);
                        }
                        if (updateDtos.Length > 0)
                        {
                            TokenCodeRepo.Update(updateDtos,checkAction,updateFunc);
                        }
                        await TokenCodeRepo.UnitOfWork.SaveChangesAsync();
                        return new OperationResult(OperationResultType.Success, "保存成功");
                    }
                    catch(Exception e)
                    {
                        return new OperationResult(OperationResultType.Error, e.Message);
                    }
                }

                /// <summary>
                /// 删除TokenCode信息
                /// </summary>
                /// <param name="ids">要删除的Id编号</param>
                /// <returns>业务操作结果</returns>
                public async Task<OperationResult> DeleteTokenCodes(params int[] ids)
                {
                    ids.CheckNotNull("ids");
                    await TokenCodeRepo.RecycleAsync(p=>ids.Contains(p.Id));
                    return new OperationResult(OperationResultType.Success, "删除成功");
                }

                #endregion

                	}
}
